//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    
    public partial class Sp_OrderForPDFHousingVisits_Result1
    {
        public int VisitID { get; set; }
        public string CustomerName { get; set; }
        public string CityName { get; set; }
        public string Address { get; set; }
        public string Phone1 { get; set; }
        public string ArchitectName { get; set; }
        public string ArchitectNumber { get; set; }
        public string ContractorName { get; set; }
        public string ContractorNumber { get; set; }
        public Nullable<decimal> EstimatedValue { get; set; }
        public Nullable<System.DateTime> NextVisitDate { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string SaleofficerName { get; set; }
        public string OffTakeFromOthers { get; set; }
        public string Scope { get; set; }
        public string Nature { get; set; }
        public string ConstructionStage { get; set; }
        public string PlotSize { get; set; }
        public string ColorScheme { get; set; }
        public string SiteWon { get; set; }
        public string CompititorName { get; set; }
        public string OnlineOffline { get; set; }
    }
}
