//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_KPITargetsRegionWise
    {
        public int ID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> ReadyMixTarget { get; set; }
        public Nullable<int> ACTDTarget { get; set; }
        public Nullable<int> CoatingTarget { get; set; }
        public Nullable<int> TotalTarget { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
