//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_HousingSiteVerification
    {
        public int ID { get; set; }
        public Nullable<int> SOID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string SiteStatus { get; set; }
        public string SiteStatusVerification { get; set; }
        public string SOMonthlyVisits { get; set; }
        public string PlotSize { get; set; }
        public string PlotType { get; set; }
        public string CompititorName { get; set; }
        public string SiteContactInfo { get; set; }
        public string SiteAddressinfo { get; set; }
        public Nullable<decimal> EstimatedValue { get; set; }
        public Nullable<long> EstimatedVolume { get; set; }
        public string Remarks { get; set; }
        public string Picture { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
