//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ProductDetail
    {
        public int ID { get; set; }
        public Nullable<int> T_ID { get; set; }
        public Nullable<int> Brand_ID { get; set; }
        public Nullable<int> Brand_Desc { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public string Product_Code { get; set; }
        public string Product_Type { get; set; }
        public string Product_Desc { get; set; }
        public Nullable<int> Tier_ID { get; set; }
        public string Tier_Desc { get; set; }
        public Nullable<int> Packing_ID { get; set; }
        public string Packing_Desc { get; set; }
        public Nullable<decimal> UOM { get; set; }
        public Nullable<int> Uom_ID { get; set; }
        public string Uom_Name { get; set; }
        public Nullable<decimal> Drum_Price { get; set; }
        public Nullable<decimal> Drum_UoM { get; set; }
        public Nullable<decimal> Gallon_Price { get; set; }
        public Nullable<decimal> Gallon_UoM { get; set; }
        public Nullable<decimal> Qtr_Price { get; set; }
        public Nullable<decimal> Qtr_UoM { get; set; }
        public Nullable<decimal> TaxableCost { get; set; }
        public string Incentive_Category { get; set; }
        public Nullable<decimal> Incentive_PKR { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> Sortorder { get; set; }
        public Nullable<decimal> Coverage { get; set; }
        public string ApplicationType { get; set; }
    }
}
