//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ChemCustomerInfo
    {
        public int ID { get; set; }
        public string BusinessName { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Code { get; set; }
        public string BusinessLine { get; set; }
        public string City { get; set; }
        public string SalesPerson { get; set; }
        public string TeamLeader { get; set; }
        public string Region { get; set; }
        public string ContactName { get; set; }
    }
}
