//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ClaimDetail
    {
        public int ID { get; set; }
        public Nullable<int> ClaimMasterID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<decimal> Drum { get; set; }
        public Nullable<decimal> Gallon { get; set; }
        public Nullable<decimal> Quarter { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<decimal> SaleLineValue { get; set; }
        public Nullable<decimal> DrumRate { get; set; }
        public Nullable<decimal> GallonRate { get; set; }
        public Nullable<decimal> QtrRate { get; set; }
    }
}
