//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Targets
    {
        public int ID { get; set; }
        public Nullable<int> HeadID { get; set; }
        public Nullable<int> SOID { get; set; }
        public Nullable<System.DateTime> FinancialYear { get; set; }
        public Nullable<int> VisitsTargetsTrade { get; set; }
        public Nullable<int> VisitsTargetsHousing { get; set; }
        public Nullable<int> VisitsTargetsCorporate { get; set; }
        public Nullable<int> NewCustomerTrade { get; set; }
        public Nullable<int> NewCustomerHousing { get; set; }
        public Nullable<int> NewCustomerCorporate { get; set; }
        public Nullable<int> SaleTrade { get; set; }
        public Nullable<int> SaleHousing { get; set; }
        public Nullable<int> SaleCorporate { get; set; }
        public Nullable<int> RecoveriesTrade { get; set; }
        public Nullable<int> RecoveriesHousing { get; set; }
        public Nullable<int> RecoveriesCorporate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedON { get; set; }
    }
}
