//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AllPurposeVisits
    {
        public int ID { get; set; }
        public Nullable<int> PurposeOfVisitID { get; set; }
        public Nullable<int> SOID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> NextVisitDate { get; set; }
        public string OtherText { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> OnlineOffline { get; set; }
    }
}
