//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BusinessAffiliates
    {
        public int ID { get; set; }
        public string BusinessName { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Address { get; set; }
        public Nullable<int> AffBusinessTypeID { get; set; }
        public Nullable<int> AffClassificationID { get; set; }
        public string AffCompititors { get; set; }
        public Nullable<int> AffExpertiseID { get; set; }
        public Nullable<int> AffNatureOfClientID { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ContactNumber { get; set; }
        public Nullable<int> SOID { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> NoOfSites { get; set; }
    }
}
