//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DetailCoverage
    {
        public int ID { get; set; }
        public Nullable<int> CoverageMasterID { get; set; }
        public Nullable<decimal> AreainSqft { get; set; }
        public Nullable<decimal> AreaInMeters { get; set; }
        public string Category { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> NoOfCoats { get; set; }
        public Nullable<decimal> Liters { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<decimal> Drum { get; set; }
        public Nullable<decimal> Gallon { get; set; }
        public Nullable<decimal> Quarter { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
