//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BrightoChemicalProducts
    {
        public int ID { get; set; }
        public Nullable<int> TID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public string BrandDesc { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ProductCode { get; set; }
        public string ProductDesc { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> TierID { get; set; }
        public string TierDesc { get; set; }
        public string SubProductDesc { get; set; }
        public Nullable<int> SubProductID { get; set; }
        public Nullable<int> PackingID { get; set; }
        public string PackingDesc { get; set; }
        public Nullable<decimal> UOM { get; set; }
        public Nullable<int> UomID { get; set; }
        public string UomName { get; set; }
        public Nullable<decimal> TaxableCost { get; set; }
    }
}
