//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_HousingVisits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_HousingVisits()
        {
            this.Tbl_HousingTradeCustomers = new HashSet<Tbl_HousingTradeCustomers>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string ArchitectName { get; set; }
        public string ArchitectNumber { get; set; }
        public string ContractorName { get; set; }
        public string ContractorNumber { get; set; }
        public Nullable<int> ScopeOfWorkID { get; set; }
        public Nullable<int> NatureOfWorkID { get; set; }
        public Nullable<int> ConstructionStageID { get; set; }
        public Nullable<int> ApproxCoveredArea { get; set; }
        public Nullable<decimal> EstimatedValue { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> NextVisitDate { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> SOID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string OffTakeFromOthers { get; set; }
        public Nullable<bool> ColorScheme { get; set; }
        public Nullable<bool> SiteWon { get; set; }
        public Nullable<int> PlotSize { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<int> OrderVolume { get; set; }
        public Nullable<int> OnlineOffline { get; set; }
        public Nullable<System.DateTime> SiteWonMonth { get; set; }
        public string Picture1 { get; set; }
        public string Picture2 { get; set; }
    
        public virtual Retailer Retailer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_HousingTradeCustomers> Tbl_HousingTradeCustomers { get; set; }
    }
}
