//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DetailKPI
    {
        public int ID { get; set; }
        public string FocusArea { get; set; }
        public Nullable<decimal> TargetValue { get; set; }
        public Nullable<decimal> TargetPercentage { get; set; }
        public Nullable<int> KPIMasterID { get; set; }
    }
}
