//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SalesClaimMaster
    {
        public int ID { get; set; }
        public Nullable<int> SOID { get; set; }
        public Nullable<int> SegmentID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> TradeEmployeeID { get; set; }
        public Nullable<int> TradePartyID { get; set; }
        public Nullable<decimal> TotalLiters { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> DateSelected { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Status { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string Picture { get; set; }
        public Nullable<decimal> SaleValue { get; set; }
        public string ClaimManagerLatestStatus { get; set; }
        public string ClaimManagerLatestRemarks { get; set; }
        public Nullable<System.DateTime> ClaimManagerDate { get; set; }
    }
}
