//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_HousingTradeCustomers
    {
        public int ID { get; set; }
        public Nullable<int> HousingVisitID { get; set; }
        public Nullable<int> TradeCustomerID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Retailer Retailer { get; set; }
        public virtual Tbl_HousingVisits Tbl_HousingVisits { get; set; }
    }
}
