//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ClaimsApproval
    {
        public int ID { get; set; }
        public Nullable<int> ClaimID { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Remarks { get; set; }
        public string ApprovedStatus { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
