//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Payments
    {
        public int ID { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> SegmentTypeid { get; set; }
        public Nullable<int> SOID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Remarks { get; set; }
        public string Picture { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<decimal> Lattitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
    }
}
