//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SaveCall
    {
        public int ID { get; set; }
        public Nullable<int> VisitID { get; set; }
        public Nullable<System.DateTime> CallDate { get; set; }
        public string CustomerType { get; set; }
        public string ConstructionStage { get; set; }
        public string SiteStatus { get; set; }
        public string Category { get; set; }
        public string NextExpectedVisit { get; set; }
        public string CallerName { get; set; }
        public string NatureOfCall { get; set; }
        public string CallRating { get; set; }
        public string Objections { get; set; }
        public string CallerRemarks { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
