//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CorporateVisits
    {
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string ProjectTitle { get; set; }
        public Nullable<int> IndustryID { get; set; }
        public string OEMName { get; set; }
        public Nullable<decimal> ProjectEstimatedValue { get; set; }
        public string InfluencerName { get; set; }
        public string InfluencerNumber { get; set; }
        public string ArchitectName { get; set; }
        public string ArchitectNumber { get; set; }
        public string BuilderName { get; set; }
        public string BuilderNumber { get; set; }
        public string PaintContractorName { get; set; }
        public string PaintContractorNumber { get; set; }
        public string ProcurementManager { get; set; }
        public string ProcurementManagerNo { get; set; }
        public string AccountsManager { get; set; }
        public string AccountsManagerNo { get; set; }
        public string CompetitorName { get; set; }
        public string CompetitorNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> SOID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<System.DateTime> NextVisitDate { get; set; }
        public Nullable<int> OrderVolume { get; set; }
        public Nullable<int> OnlineOffline { get; set; }
    
        public virtual Retailer Retailer { get; set; }
    }
}
